default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['RIPPER_DATABASE_USERNAME'] %>
  password: <%= ENV['RIPPER_DATABASE_PASSWORD'] %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: ripper_development

test:
  <<: *default
  database: ripper_test

production:
  <<: *default
  host: ripper
  database: ripper_production
