default: &default
  adapter: mysql2
  encoding: utf8
  pool: 25
  username: <%= ENV['RIPPER_DATABASE_USERNAME'] %>
  password: <%= ENV['RIPPER_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: ripper_development

test:
  <<: *default
  database: ripper_test

production:
  <<: *default
  host: ripper
  database: ripper_production
