default: &default
  adapter: postgresql
  encoding: utf8
  pool: 25
  
development:
  <<: *default
  database: ripper_development

test:
  <<: *default
  database: ripper_test

production:
  <<: *default
  host: ripper
  database: ripper_production
