---
:concurrency: 5
:pidfile: tmp/pids/sidekiq.pid
# :logfile: log/sidekiq.log
staging:
  :concurrency: 5
production:
  :concurrency: 5
:queues:
  - [critical, 20]
  - [Comic, 10]
  - [default, 5]
  - [Chapter, 5]
  - [Page, 1]
