require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ComicsController do
  pending "No!"
<<COMMENT
  # This should return the minimal set of attributes required to create a valid
  # Comic. As you add validations to Comic, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ComicsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all comics as @comics" do
      comic = Comic.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:comics)).to eq([comic])
    end
  end

  describe "GET show" do
    it "assigns the requested comic as @comic" do
      comic = Comic.create! valid_attributes
      get :show, {:id => comic.to_param}, valid_session
      expect(assigns(:comic)).to eq(comic)
    end
  end

  describe "GET new" do
    it "assigns a new comic as @comic" do
      get :new, {}, valid_session
      expect(assigns(:comic)).to be_a_new(Comic)
    end
  end

  describe "GET edit" do
    it "assigns the requested comic as @comic" do
      comic = Comic.create! valid_attributes
      get :edit, {:id => comic.to_param}, valid_session
      expect(assigns(:comic)).to eq(comic)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Comic" do
        expect {
          post :create, {:comic => valid_attributes}, valid_session
        }.to change(Comic, :count).by(1)
      end

      it "assigns a newly created comic as @comic" do
        post :create, {:comic => valid_attributes}, valid_session
        expect(assigns(:comic)).to be_a(Comic)
        expect(assigns(:comic)).to be_persisted
      end

      it "redirects to the created comic" do
        post :create, {:comic => valid_attributes}, valid_session
        expect(response).to redirect_to(Comic.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved comic as @comic" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Comic).to receive(:save).and_return(false)
        post :create, {:comic => { "title" => "invalid value" }}, valid_session
        expect(assigns(:comic)).to be_a_new(Comic)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Comic).to receive(:save).and_return(false)
        post :create, {:comic => { "title" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

COMMENT
end
